Modified /api/articles/:article_id/comments acording to ticket to ret…
Jorge-Figueira/NC-News-Backend pull request #7
Opened 2022-02-17 16:02 UTC by Jorge-Figueira

…urn the comment count for the requeired article

2022-02-17 16:39 UTC, Angaca requested changes
xomment_count should be included in the PSQL query that should be modified accordingly and so your tests. Plus I don't know what those mystery variables are but they shouldn't be there

2022-02-18 10:37 UTC, Angaca commented on models/news.models.js
> +            return parseInt(rows[0].count)
I was thinking more of a one single big PQSL statement but this can work too

2022-02-18 10:38 UTC, Angaca commented on controllers/news.controllers.js
> +            const retrunObject = {article, comment_count}
This is not fine, comment_count should be a key/value inside the object and you should still send a single {article}

2022-02-18 10:40 UTC, Angaca requested changes
Almost there. comment_count needs to be a property of article. You should send a single article object as well. You can either refactor you PSQL model statement to generate a new column with the count (more efficient as you do only one query to the DB) or adding a new line in your controller when you attach comment_count to your article and send that single article back. Either way your test needs amending for the new outcome

2022-02-18 15:40 UTC, DCrawley94 reviewed
Looks like it's working, you could extract one of the db.querys into a new file as a checkArticlesExists helper function but looks like your way works too.

You can always come back at a later date to refactor these things :)

2022-02-18 15:46 UTC, merged